// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://euphgaysatzuneafbwzu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1cGhnYXlzYXR6dW5lYWZid3p1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NjMzNDIsImV4cCI6MjA2MTMzOTM0Mn0.3bFqCSvm_QfUWwUzJ_iSqGmLumdusrjjANmu8Y7bONA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);